version: '3'

services:
  mysql:
    image: mysql:5.6
    container_name: tc-integracion-mysql
    environment:
      MYSQL_DATABASE: db_techmark
      MYSQL_USER: my_username
      MYSQL_PASSWORD: my_password
      MYSQL_ROOT_PASSWORD: my_password
    ports:
      - "3306:3306"
    restart: always

  web:
    image: php:7.3-apache
    container_name: tc-integracion-php
    ports:
      - "80:80"
    volumes:
      - ./www:/var/www/html
    links:
      - mysql
